<h1>
<?php switch ($breadcrumbs['controlador']) : ?>
<?php case 'index' : ?>
    Starter Page <small>it all starts here</small>
<?php break ?>
<?php endswitch ?>
</h1>

<ol class="breadcrumb">
<?php switch ($breadcrumbs['controlador']) : ?>
<?php case 'index' : ?>
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
<?php break ?>
<?php endswitch ?>
    <li class="active">
        <?= ucfirst($breadcrumbs['accion']) . ' Action' ?>
    </li>
</ol>
