<h1>
<?php switch ($breadcrumbs['controlador']) : ?>
<?php case 'pages' : ?>
Config Page <small>framework configurations</small>
<?php break ?>
<?php case 'profile' : ?>
User Profile <small>complete information</small>
<?php break ?>
<?php default : ?>
Starter Page <small>it all starts here</small>
<?php endswitch ?>
</h1>

<ol class="breadcrumb">
    <?php if ($breadcrumbs['controlador'] === 'index') : # Case Index ?>
    <li><?= MyHtml::link('', '<i class="fa fa-dashboard"></i> Home</a>') ?></li>
    <li class="active">Starter</li>
    <?php elseif ($breadcrumbs['controlador'] === 'pages') : # Case Pages ?> 
    <li><?= MyHtml::link('', '<i class="fa fa-dashboard"></i> Home</a>') ?></li>
    <li class="active"><?= ucfirst($breadcrumbs['accion']) ?></li>
    <?php else : # Rest of cases ?> 
    <li><?= MyHtml::link('', '<i class="fa fa-dashboard"></i> Home</a>') ?></li>
    <li><?= MyHtml::link($breadcrumbs['controlador'] . '/', ucfirst($breadcrumbs['controlador'])) ?></li>
    <li class="active"><?= ucfirst($breadcrumbs['accion']) ?></li>
    <?php endif ?>
</ol>
