<?php Html::meta(null, 'charset="utf-8"') ?>
<?php Html::meta('IE=edge', 'http-equiv="X-UA-Compatible"') ?>
<?php Html::meta('width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', 'name="viewport"') ?>
<?= Html::includeMetatags() ?>

<?php switch ($breadcrumbs['controlador']) : ?>
<?php case 'lock': ?>
<title>Curso CRUD | Lockscreen</title>
<?php break ?>
<?php case 'login': ?>
<title>Curso CRUD | Log in</title>
<?php break ?>
<?php case 'register' : ?>
<title>Curso CRUD | Registration</title>
<?php break ?>
<?php case 'profile' : ?>
<title>Curso CRUD | User Profile</title>
<?php break ?>
<?php default : ?>
<title>Curso CRUD | Starter</title>
<?php endswitch ?>

<?php Html::headLinkResource('img/adminlte/img/favicon.ico', 'rel="shortcut icon" type="image/x-icon"') ?>
<?php Html::headLinkResource('css/adminlte/bootstrap/css/bootstrap.min.css', 'rel="stylesheet"') ?>
<?php Html::headLinkResource('css/adminlte/font-awesome/css/font-awesome.min.css', 'rel="stylesheet"') ?>
<?php Html::headLinkResource('css/adminlte/Ionicons/css/ionicons.min.css', 'rel="stylesheet"') ?>
<?php Html::headLinkResource('css/adminlte/css/AdminLTE.min.css', 'rel="stylesheet"') ?>

<?php switch ($breadcrumbs['controlador']) : ?>
<?php case 'lock' : ?>
<!-- Lockscreen -->
<?php break ?>
<?php case 'login' : ?>
<?php case 'register' : ?>
<?php Html::headLinkResource('css/adminlte/iCheck/square/blue.css', 'rel="stylesheet"') ?>
<?php break ?>
<?php case 'profile' : ?>
<?php Html::headLinkResource('css/adminlte/iCheck/square/blue.css', 'rel="stylesheet"') ?>
<?php Html::headLinkResource('css/adminlte/css/skins/_all-skins.min.css', 'rel="stylesheet"') ?>
<?php break ?>
<?php default : ?>
<?php Html::headLinkResource('css/adminlte/css/skins/_all-skins.min.css', 'rel="stylesheet"') ?>
<?php endswitch ?>

<?php Html::headLinkResource('css/adminlte/styles.css', 'rel="stylesheet"') ?>
<?php Html::headLink('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic', 'rel="stylesheet"') ?>
<?= Html::includeHeadLinks() ?>

<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
