<!-- Sidebar toggle button-->
<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>

<div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
        <!-- Search Form (optional)
        <li>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                </div>
            </form>
        </li>
        -->
        <?php # View::partial('adminlte/navbar/messages') ?>
        
        <?php # View::partial('adminlte/navbar/notifications') ?>
        
        <?php # View::partial('adminlte/navbar/tasks') ?>
        
        <?php View::partial('adminlte/navbar/account') ?>
        
        <!-- Control Sidebar Toggle Button 
        <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
        -->
    </ul>
</div>
