<section class="sidebar">
    <!-- Sidebar user panel (optional) 
    <div class="user-panel">
        <div class="pull-left image">
            <?= Html::img('adminlte/img/user2-160x160.jpg', 'User Image', 'class="img-circle"') ?>
        </div>
        <div class="pull-left info">
            <p>Alexander Pierce</p>
            <?= Html::link('index', '<i class="fa fa-circle text-success"></i> Online') ?>
        </div>
    </div>
    -->
    
    <!-- search form (Optional) 
    <?= Form::open('', 'post', 'class="sidebar-form"') ?>
        <div class="input-group">
            <?= Form::text('q', 'class="form-control" placeholder="Search..."') ?>
            <span class="input-group-btn">
                <?= Form::submit('<i class="fa fa-search"></i>', 'name="search" id="search-btn" class="btn btn-flat"') ?>
            </span>
        </div>
    <?= Form::close() ?>
    -->
    
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <!--
        <li class="active">
            <a href="#"><i class="fa fa-link"></i> <span>Link</span></a>
        </li>
        -->
        <li class="treeview active">
            <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="active"><?= Html::link('index', '<i class="fa fa-check-circle-o"></i> Start Page') ?></li>
                <li><?= Html::link('lock', '<i class="fa fa-circle-o"></i> Lock Page') ?></li>
                <li><?= Html::link('login', '<i class="fa fa-circle-o"></i> Login Page') ?></li>
                <li><?= Html::link('register', '<i class="fa fa-circle-o"></i> Register Page') ?></li>
            </ul>
        </li>
    </ul>
</section>
