<p class="login-box-msg">Sign in to start your session</p>

<?= Form::open('', 'post') ?>
<div class="form-group has-feedback">
    <?= Form::input('email', 'username', 'class="form-control" placeholder="Email"') ?>
    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
</div>
<div class="form-group has-feedback">
    <?= Form::pass('userpass', 'class="form-control" placeholder="Password"') ?>
    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
</div>
<div class="row">
    <div class="col-xs-8">
        <div class="checkbox icheck">
            <label>
                <?= Form::check('rememberme', '1') ?> Remember Me
            </label>
        </div>
    </div>
    <div class="col-xs-4">
        <?= Form::submit('Sign In', 'class="btn btn-primary btn-block btn-flat"') ?>
    </div>
</div>
<?= Form::close() ?>

<!--
<div class="social-auth-links text-center">
    <p>- OR -</p>
    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
</div>
-->

<!-- <a href="#">I forgot my password</a><br> -->

<?= MyHtml::link('register/', 'Register a new membership', 'class="text-center"') ?>
