<div class="box box-primary">
	<div class="box-body box-profile">
		<?= Html::img('adminlte/img/user6-128x128.jpg', 'User profile picture', 'class="profile-user-img img-responsive img-circle"') ?>
		<h3 class="profile-username text-center"><?= ucwords($usuario->nick) ?></h3>
		<p class="text-muted text-center">Software Engineer</p>

		<ul class="list-group list-group-unbordered">
			<li class="list-group-item">
				<b>Followers</b> <a class="pull-right">1,322</a>
			</li>
			<li class="list-group-item">
				<b>Following</b> <a class="pull-right">543</a>
			</li>
			<li class="list-group-item">
				<b>Friends</b> <a class="pull-right">13,287</a>
			</li>
		</ul>

		<a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
	</div>
    <!-- /.box-body -->
</div>
<!-- /.box -->
