<div class="active tab-pane" id="settings">
	<?= Form::open("profile/edit/{$usuario->id}", 'post', 'class="form-horizontal"') ?>
		<div class="form-group">
			<?= Form::label('Name', 'users_nick', 'class="col-sm-2 control-label"') ?>
			<div class="col-sm-10">
				<?= Form::text('users.nick', 'class="form-control" placeholder="Name" required="required" autofocus="autofocus"', ucwords($usuario->nick)) ?>
			</div>
		</div>
		<div class="form-group">
			<?= Form::label('Email', 'users_mail', 'class="col-sm-2 control-label"') ?>
			<div class="col-sm-10">
				<?= Form::input('email', 'users.mail', 'class="form-control" placeholder="Email" required="required"', $usuario->mail) ?>
			</div>
		</div>
		<div class="form-group">
			<?= Form::label('Password', 'users_pass', 'class="col-sm-2 control-label"') ?>
			<div class="col-sm-10">
				<?= Form::pass('users.pass', 'class="form-control" placeholder="Password"') ?>
				<p class="help-block">(*) Optional data field.</p>
			</div>
		</div>
		<div class="form-group">
			<?= Form::label('Experience', 'users_bio', 'class="col-sm-2 control-label"') ?>
			<div class="col-sm-10">
				<?= Form::textarea('users.bio', 'class="form-control" placeholder="Experience"', $usuario->bio) ?>
			</div>
		</div>
		<!--
		<div class="form-group">
			<label for="inputSkills" class="col-sm-2 control-label">Skills</label>

			<div class="col-sm-10">
				<input type="text" class="form-control" id="inputSkills" placeholder="Skills">
			</div>
		</div>
		-->
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<div class="checkbox icheck">
					<label>
						<?= Form::check('iagree', '1') ?> I agree to the <a href="#">terms and conditions</a>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<?= Form::submit('Submit', 'class="btn btn-primary"') ?>
			</div>
		</div>
	</form>
</div>
