<div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
        <img src="http://localhost/pruebas/img/adminlte/img/user1-128x128.jpg" alt="User Image">
    </div>
    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials">
        <div class="input-group">
            <input type="password" class="form-control" placeholder="password">

            <div class="input-group-btn">
                <button type="button" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
            </div>
        </div>
    </form>
</div>

<div class="help-block text-center">
    Enter your password to retrieve your session
</div>

<div class="text-center">
    <a href="login.html">Or sign in as a different user</a>
</div>

<div class="lockscreen-footer text-center">
    Copyright &copy; 2014-2016 <b><a href="https://adminlte.io" class="text-black">Almsaeed Studio</a></b><br>
    All rights reserved
</div>
