<div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
        <?= Html::img('adminlte/img/user1-128x128.jpg', 'User Image') ?>
    </div>
    <!-- lockscreen credentials (contains the form) -->
    <?= Form::open('', 'post', 'class="lockscreen-credentials"') ?>
        <div class="input-group">
            <?= Form::pass('userpass', 'class="form-control" placeholder="password"') ?>
            <div class="input-group-btn">
                <?= Form::submit('<i class="fa fa-arrow-right text-muted"></i>', 'class="btn"') ?>
            </div>
        </div>
    <?= Form::close() ?>
</div>

<div class="help-block text-center">
    Enter your password to retrieve your session
</div>

<div class="text-center">
    <?= MyHtml::link('login/', 'Or sign in as a different user') ?>
</div>

<div class="lockscreen-footer text-center">
    Copyright &copy; <?= date('Y') ?> <b><a href="#" class="text-black">Álvaro Gordillo Reina</a></b><br>
    All rights reserved
</div>
