<p class="login-box-msg">Register a new membership</p>

<?= Form::open('', 'post') ?>
<div class="form-group has-feedback">
    <?= Form::text('username', 'class="form-control" placeholder="Full name"') ?>
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
</div>
<div class="form-group has-feedback">
    <?= Form::input('email', 'usermail', 'class="form-control" placeholder="Email"') ?>
    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
</div>
<div class="form-group has-feedback">
    <?= Form::pass('userpass1', 'class="form-control" placeholder="Password"') ?>
    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
</div>
<div class="form-group has-feedback">
    <?= Form::pass('userpass2', 'class="form-control" placeholder="Retype password"') ?>
    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
</div>
<div class="row">
    <div class="col-xs-8">
        <div class="checkbox icheck">
            <label>
                <?= Form::check('iagree', '1') ?> I agree to the <a href="#">terms</a>
            </label>
        </div>
    </div>
    <div class="col-xs-4">
        <?= Form::submit('Register', 'class="btn btn-primary btn-block btn-flat"') ?>
    </div>
</div>
<?= Form::close() ?>

<!--
<div class="social-auth-links text-center">
    <p>- OR -</p>
    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
        Facebook</a>
    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using
        Google+</a>
</div>
-->

<?= MyHtml::link('login/', 'I already have a membership', 'class="text-center"') ?>
