<div class="row">
	<div class="col-md-3">
		<!-- Profile Image -->
		<?php View::partial('adminlte/profile/profile_image') ?>
	</div>
	<div class="col-md-9">
		<div class="nav-tabs-custom">
			<ul class="nav nav-tabs" id="myTabs">
				<li class="active"><a href="#settings" data-toggle="tab">Settings</a></li>
				<li><a href="#about_me" data-toggle="tab">About Me</a></li>
				<!--
				<li><a href="#activity" data-toggle="tab">Activity</a></li>
				<li><a href="#timeline" data-toggle="tab">Timeline</a></li>
				-->
			</ul>
			<div class="tab-content">
				<?php View::partial('adminlte/profile/settings') ?>
				<?php View::partial('adminlte/profile/about_me') ?>
				<?php # View::partial('adminlte/profile/activity') ?>
				<?php # View::partial('adminlte/profile/timeline') ?>
			</div>
		</div>
	</div>
</div>
