<?php
// Controlando si se ejecuta en windows para que no de problemas la funcion
if (PHP_OS == 'WINNT') {
    echo strftime("%#d de %B del %Y"), '<br/>';
} else {
    # echo strftime("%e de %B del %Y"), '<br/>';
}

/**
 * Verificando permisos del dir temp/
 */
if (!is_writable(APP_PATH . 'temp')) {
    $tmp = "Debes darle permiso a: '" . basename(APP_PATH) . "/temp/'";
} else {
    $tmp = 'Directorio temp... ok';
}

$status = PRODUCTION ? 'Production' : 'Development';

/**
 * Configuracion del config.ini
 */
$config = Config::read('config');

if (isset($config['application']['cache_driver'])) {
    $cahe_driver = $config['application']['cache_driver'];
} else {
    $cache_driver = 'No ha seleccionado un driver para la cache';
}

$locale = str_replace(';', '<br>', setlocale(LC_ALL, '0'));

if (!$timezone = date_default_timezone_get()) {
    $timezone = 'No se ha especificado un Timezone.';
}
?>

<div class="row">
    <div class="col-sm-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">config.ini <span class='app'> en modo... <?= basename(dirname(APP_PATH)) ?></span></h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <h4>Directorio temp/:</h4>
                <p><?= $tmp ?></p>

                <h4>Estado Actual del Framework: <span><?= $status ?></span></h4>
                <p>Ver <a href='http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#Modos_de_una_Aplicaci.C3.B3n'>Modos de ejecución</a></p>

                <h4>Base de Datos: <span><?= $config['application']['database'] ?></span></h4>
                <p>Datos de la conexión a la BD que será utilizada, ver configuración <a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">databases.ini</a>.</p>

                <h4>Cache Driver: <span><?= $cahe_driver ?></span></h4>
                <p>Driver que se utilizará para realizar las operaciones de cache.</p>

                <h4>Charset: <span><?= APP_CHARSET ?></span></h4>
                <p>Codificación de caracteres. Recomendado UTF-8</p>
            </div>
        </div>    
    </div>
    <div class="col-sm-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Valores del servidor</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <h4>TimeZone: <span><?= $timezone ?></span></h4>
                <p>Zona horaria que usará la aplicación.</p>
                <h4>Locale:</h4>
                <span><?= $locale ?></span>
                <p>Localización. Característica que depende de los locale instalados en el servidor.</p>
            </div>
        </div>
    </div>
</div>
