<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">KumbiaPHP <?= kumbia_version() ?> está listo para usarse</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <h2>Bienvenido a KumbiaPHP Framework</h2>
        <p>El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente, sin tener que reinventar la rueda, y preocupándose por lo más importante, la lógica de su aplicación.</p>
        <h2>Cómo empezar</h2>
        <p>En nuestra <a href="http://wiki.kumbiaphp.com/">wiki</a> podrás encontrar información actualizada sobre el uso del framework,
            si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
            <strong><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>.</p>
        <p>También puede interesarte saber sobre:</p>
        <ul>
            <li><a href="http://wiki.kumbiaphp.com/V1.0_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></h3></li>
            <li><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></li>
            <li><a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">Configurar conexiones a bases de datos</a></li>
        </ul>
        <p>Estos son sólo algunos ejemplos, puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p>    
    </div>
    <!--
    <div class="box-footer">
        <p class="pull-right"><?= Html::link('pages/show/kumbia/status/', 'Ver Config', 'title="Ver configuración de la aplicación" class="btn btn-info"') ?></p>
    </div>
    -->
</div>
