<!DOCTYPE html>
<html lang="es-ES">
    <head>
        <?php View::partial('adminlte/head_links', NULL, array('breadcrumbs' => $breadcrumbs)) ?>
    </head>
    <body class="hold-transition register-page">
        <div class="register-box">
            <div class="register-logo">
                <?= MyHtml::link('', '<b>Admin</b>LTE') ?>
            </div>
            <div class="register-box-body">
                <?php View::content() ?>
            </div>
        </div>
        <!-- Scrtips JS -->
        <?php View::partial('adminlte/scripts_js', NULL, array('breadcrumbs' => $breadcrumbs)) ?>
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' /* optional */
                });
            });
        </script>
    </body>
</html>
