<!DOCTYPE html>
<html lang="es-ES">
    <head>
        <?php View::partial('adminlte/head_links', NULL, array('breadcrumbs' => $breadcrumbs)) ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <!-- Site Wrapper -->
        <div class="wrapper">
            <!-- Main Header -->
            <header class="main-header">
                <!-- Logo -->
                <?php View::partial('adminlte/logo') ?>
                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top">
                    <?php View::partial('adminlte/navbar_main') ?>
                </nav>
            </header>
            <!-- Left side column. Contains the sidebar -->
            <aside class="main-sidebar">
                <?php View::partial('adminlte/sidebar') ?>
            </aside>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <?php View::partial('adminlte/content_header', NULL, array('breadcrumbs' => $breadcrumbs)) ?>
                </section>
                <!-- Main content -->
                <section class="content">
                    <?php View::content() ?>
                </section>
            </div>
            <!-- Main Footer -->
            <footer class="main-footer">
                <?php View::partial('adminlte/footer') ?>
            </footer>
            <!-- Control Sidebar 
            <aside class="control-sidebar control-sidebar-dark">
                <?php # View::partial('adminlte/control_sidebar') ?>
            </aside>
            -->
            <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar 
            <div class="control-sidebar-bg"></div>
            -->
        </div>
        <!-- Scrtips JS -->
        <?php View::partial('adminlte/scripts_js', NULL, array('breadcrumbs' => $breadcrumbs)) ?>
    </body>
</html>
